[project]
name = "overwatch"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "celery>=5.5.2",
    "django>=5.2.1",
    "django-celery-results>=2.6.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.9",
]
