# Generated by Django 5.2.1 on 2025-05-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Frame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="frames")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("embeddings", models.JSONField(default=list)),
            ],
        ),
    ]
