# Generated by Django 5.2.1 on 2025-05-25 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frame",
            name="embeddings",
        ),
    ]
