# Generated by Django 5.2.1 on 2025-06-10 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_detectedobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedobject',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='ingest.frame'),
        ),
    ]
