# Generated by Django 5.2.1 on 2025-06-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0006_alter_detectedobject_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
