# Generated by Django 5.2.1 on 2025-06-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0006_alter_detectedobject_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, help_text='Match specific object label (optional)', max_length=100)),
                ('min_confidence', models.FloatField(default=0.0, help_text='Minimum confidence threshold (0-1)')),
                ('text_contains', models.CharField(blank=True, help_text='Case-insensitive substring search on OCR text', max_length=200)),
                ('description', models.CharField(blank=True, help_text='Natural language description for the alert rule (auto embedded)', max_length=200)),
                ('embedding', models.JSONField(blank=True, help_text='Reference embedding vector (list of floats) for cosine similarity', null=True)),
                ('max_distance', models.FloatField(default=0.3, help_text='Max cosine distance to trigger alert (lower = stricter)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('detection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.detectedobject')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.frame')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.alertrule')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
