# Generated by Django 5.2.1 on 2025-06-30 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0003_alter_alertrule_min_similarity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrule",
            name="min_similarity",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Minimum CLIP similarity score (0-100) required to trigger this rule",
            ),
        ),
        migrations.CreateModel(
            name="AlertReferenceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="alert_refs")),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_images",
                        to="alerts.alertrule",
                    ),
                ),
            ],
        ),
    ]
